PizzaPlace/ViewModels/MenuViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PizzaPlace.ViewModels
{
    public class MenuViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public double Price { get; set; }
        [Required]
        public string ImageUrl { get; set; }
        public DateTime DateCreated { get; set; }
    }
}

PizzaPlace/Pages/Dashboard/CreateMenuItem.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System;

namespace PizzaPlace.Pages.Dashboard
{
    [Authorize(Roles = "Admin")]
    public class CreateMenuItemModel : PageModel
    {
        private readonly IMenuItemService menuItemService;

        public CreateMenuItemModel(IMenuItemService menuItemService)
        {
            this.menuItemService = menuItemService;
        }
        [BindProperty]
        public MenuViewModel MenuItem { get; set; }
        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                MenuItem menuItem = new MenuItem() 
                {
                    Title = MenuItem.Title,
                    ImageUrl = MenuItem.ImageUrl,
                    Description = MenuItem.Description,
                    Price = MenuItem.Price,
                    DateCreated = DateTime.Now,
                };
                menuItemService.Add(menuItem);
                return RedirectToPage("MenuItemsList");
            }
            else
            {
                return Page();
            }
        }
    }
}

PizzaPlace/Pages/Dashboard/CreateOffer.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System;

namespace PizzaPlace.Pages.Dashboard
{ 
    [Authorize(Roles = "Admin")]
    public class CreateOfferModel : PageModel
    {
        private readonly IOfferService offerService;

        public CreateOfferModel(IOfferService offerService)
        {
            this.offerService = offerService;
        }
        [BindProperty]
        public OfferViewModel Offer { get; set; }
        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                Offer offer = new Offer();
                offer.Title = Offer.Title;
                offer.Description = Offer.Description;
                offer.Price = Offer.Price;
                offer.DateCreated = DateTime.Now;

                offerService.Create(offer);
                return RedirectToPage("OffersList");
            }
            else
            {
                return Page();
            }
        }
    }
}

PizzaPlace/Pages/Dashboard/EditMenuItem.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Custom;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;

namespace PizzaPlace.Pages.Dashboard
{
    public class EditMenuItemModel : PageModel
    {
        private readonly IMenuItemService menuItemService;

        public EditMenuItemModel(IMenuItemService menuItemService)
        {
            this.menuItemService = menuItemService;
        }
        [BindProperty]
        public MenuViewModel MenuItem { get; set; }
        public void OnGet(int id)
        {
            MenuItem = ModelConverter.ConvertToMenuItemsModel(menuItemService.GetById(id));
        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                MenuItem menuItem = ModelConverter.ConverFromMenuItemsModel(MenuItem);
                menuItemService.Update(menuItem);
                return RedirectToPage("MenuItemsList");
            }
            else
            {
                return Page();
            }
        }
    }
}

PizzaPlace/Pages/Dashboard/EditOffer.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Custom;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;

namespace PizzaPlace.Pages.Dashboard
{
    [Authorize(Roles = "Admin")]
    public class EditOfferModel : PageModel
    {
        private readonly IOfferService offerService;

        public EditOfferModel(IOfferService offerService)
        {
            this.offerService = offerService;
        }
        [BindProperty]
        public OfferViewModel Offer { get; set; }
        public void OnGet(int id)
        {
            Offer = ModelConverter.ConvertToOfferViewModel(offerService.GetById(id));
        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                Offer offer = ModelConverter.ConvertFromOfferViewModel(Offer);
                offerService.Update(offer);
                return RedirectToPage("OffersList");
            }
            else
            {
                return Page();
            }
        }
    }
}

PizzaPlace/Pages/Dashboard/FeedbacksList.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Custom;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PizzaPlace.Pages.Dashboard
{
    public class FeedbacksListModel : PageModel
    {
        private readonly IFeedbackService feedbackService;

        public FeedbacksListModel(IFeedbackService feedbackService)
        {
            this.feedbackService = feedbackService;
        }
        public List<FeedbackViewModel> Feedbacks { get; set; }
        public void OnGet()
        {
            Feedbacks = feedbackService.GetAll()
                .Select(x => ModelConverter.ConvertToFeedbackViewModel(x))
                .ToList();
        }
    }
}

PizzaPlace/Pages/Dashboard/Menu.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PizzaPlace.Pages.Dashboard
{
    [Authorize]
    public class MenuModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

PizzaPlace/Pages/Dashboard/MenuItemsList.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Custom;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PizzaPlace.Pages.Dashboard
{
    [Authorize(Roles = "Admin")]
    public class MenuItemsListModel : PageModel
    {
        private readonly IMenuItemService menuItemService;

        public MenuItemsListModel(IMenuItemService menuItemService)
        {
            this.menuItemService = menuItemService;
        }
        public List<MenuViewModel> MenuItems { get; set; }
        public void OnGet()
        {
            MenuItems = menuItemService.GetAll()
                .Select(x => ModelConverter.ConvertToMenuItemsModel(x))
                .ToList();
        }
        public IActionResult OnGetDeleteMenuItem(int id)
        {
            menuItemService.Remove(id);
            return RedirectToPage("MenuItemsList");
        }
    }
}

PizzaPlace/Pages/Dashboard/OffersList.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Custom;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PizzaPlace.Pages.Dashboard
{
    [Authorize(Roles = "Admin")]
    public class OffersListModel : PageModel
    {
        private readonly IOfferService offerService;

        public OffersListModel(IOfferService offerService)
        {
            this.offerService = offerService;
        }
        public List<OfferViewModel> Offers { get; set; }
        public void OnGet()
        {
            Offers = offerService.GetAll()
                .Select(x => ModelConverter.ConvertToOfferViewModel(x))
                .ToList();
        }
        public IActionResult OnGetDeleteOffer(int id)
        {
            offerService.Remove(id);
            return RedirectToPage("OffersList");
        }
    }
}

PizzaPlace/Pages/Dashboard/OrdersList.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Custom;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PizzaPlace.Pages
{
    [Authorize]
    public class ViewOrdersModel : PageModel
    {
        private readonly IOrderService orderService;

        public ViewOrdersModel(IOrderService orderService)
        {
            this.orderService = orderService;
        }
        public List<OrderViewModel> Orders { get; set; }
        public void OnGet()
        {
            Orders = orderService.GetAll()
                .Select(x => ModelConverter.ConvertToOrderViewModel(x))
                .ToList();
        }
        public void OnGetNotProcessed()
        {
            Orders = orderService.GetByStatus(false, false)
                .Select(x => ModelConverter.ConvertToOrderViewModel(x))
                .ToList();
        }

        public void OnGetProcessed()
        {
            Orders = orderService.GetByStatus(true, false)
                .Select(x => ModelConverter.ConvertToOrderViewModel(x))
                .ToList();
        }
        public void OnGetDone()
        {
            Orders = orderService.GetByStatus(true, true)
                .Select(x => ModelConverter.ConvertToOrderViewModel(x))
                .ToList();
        }
        public IActionResult OnGetSetProcessed(int id)
        {
            orderService.SetOrderProccessed(id);
            return RedirectToPage("OrdersList", "NotProcessed");
        }
        public IActionResult OnGetSetDelivered(int id)
        {
            orderService.SetOrderDelivered(id);
            return RedirectToPage("OrdersList", "Processed");
        }
    }
}

PizzaPlace/Pages/Dashboard/UsersList.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PizzaPlace.Pages.Dashboard
{
    [Authorize(Roles = "Admin")]
    public class UsersListModel : PageModel
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public UsersListModel(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }
        public List<IdentityUser> Users { get; set; }
        public List<IdentityRole> Roles { get; set; }
        public void OnGet()
        {
            Users = userManager.Users.ToList();
            Roles = roleManager.Roles.ToList();
        }

        public async Task<IActionResult> OnGetAddRole(string roleName, string userId)
        {
            IdentityUser user = await userManager.FindByIdAsync(userId);
            await userManager.AddToRoleAsync(user, roleName);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetRemoveRole(string roleName, string userId)
        {
            IdentityUser user = await userManager.FindByIdAsync(userId);
            await userManager.RemoveFromRoleAsync(user, roleName);
            return RedirectToPage();
        }
        public async Task<IActionResult> OnGetDeleteUser(string id)
        {
            IdentityUser user = await userManager.FindByIdAsync(id);
            await userManager.DeleteAsync(user);
            return RedirectToPage();
        }
    }
}

PizzaPlace/Pages/Menu.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PizzaPlace.Pages
{
    public class MenuModel : PageModel
    {
        private readonly IMenuItemService menuItemService;

        public MenuModel(IMenuItemService menuItemService)
        {
            this.menuItemService = menuItemService;
        }
        public List<MenuViewModel> MenuViewModels { get; set; }
        public void OnGet()
        {
            MenuViewModels = menuItemService.GetAll().Select(x => new MenuViewModel 
            {
                Id = x.Id,
                Title = x.Title,
                Description = x.Description,
                ImageUrl = x.ImageUrl,
                Price = x.Price,
                DateCreated = x.DateCreated,
            }).ToList();
        }
    }
}

PizzaPlace/Pages/Dashboard/CreateMenuItem.cshtml
@page
@model PizzaPlace.Pages.Dashboard.CreateMenuItemModel
@{
    ViewData["Title"] = "CreateMenuItem";
    Layout = "_LayoutDashboard";
}

<h1>CreateMenuItem</h1>

<div class="container" style="background-color:#dadada; margin-top:20px; padding:20px;">
    <form asp-page="CreateMenuItem" method="post">
        <div class="form-group">
            <label asp-for="@Model.MenuItem.Title">Title:</label>
            <input asp-for="@Model.MenuItem.Title" class="form-control" placeholder="Enter title">
            <span asp-validation-for="@Model.MenuItem.Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.MenuItem.ImageUrl">Image Url:</label>
            <input asp-for="@Model.MenuItem.ImageUrl" class="form-control" placeholder="Enter Image url">
            <span asp-validation-for="@Model.MenuItem.ImageUrl" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.MenuItem.Price">Price:</label>
            <input asp-for="@Model.MenuItem.Price" class="form-control" placeholder="Enter Price">
            <span asp-validation-for="@Model.MenuItem.Price" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.MenuItem.Description">Description:</label>
            <textarea asp-for="@Model.MenuItem.Description" class="form-control" placeholder="Enter Description"></textarea>
            <span asp-validation-for="@Model.MenuItem.Description" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Order</button>
    </form>
</div>

PizzaPlace/Pages/Dashboard/CreateOffer.cshtml
@page
@model PizzaPlace.Pages.Dashboard.CreateOfferModel
@{
    ViewData["Title"] = "CreateOffer";
    Layout = "_LayoutDashboard";
}

<h1>CreateOffer</h1>

<div class="container" style="background-color:#dadada; margin-top:20px; padding:20px;">
    <form asp-page="CreateOffer" method="post">
        <div class="form-group">
            <label asp-for="@Model.Offer.Title">Title:</label>
            <input asp-for="@Model.Offer.Title" class="form-control" placeholder="Enter Title">
            <span asp-validation-for="@Model.Offer.Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Offer.Description">Description:</label>
            <textarea asp-for="@Model.Offer.Description" class="form-control" placeholder="Enter Description"></textarea>
            <span asp-validation-for="@Model.Offer.Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Offer.Price">Price:</label>
            <input asp-for="@Model.Offer.Price" class="form-control">
            <span asp-validation-for="@Model.Offer.Price" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

PizzaPlace/Pages/Dashboard/EditMenuItem.cshtml
@page
@model PizzaPlace.Pages.Dashboard.EditMenuItemModel
@{
    ViewData["Title"] = "EditMenuItem";
    Layout = "_LayoutDashboard";
}

<h1>EditMenuItem</h1>

<div class="container" style="background-color:#dadada; margin-top:20px; padding:20px;">
    <form asp-page="EditMenuItem" method="post">
        <input asp-for="@Model.MenuItem.Id" type="hidden" />
        <div class="form-group">
            <label asp-for="@Model.MenuItem.Title">Title:</label>
            <input asp-for="@Model.MenuItem.Title" class="form-control" placeholder="Enter Title">
            <span asp-validation-for="@Model.MenuItem.Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.MenuItem.ImageUrl">Image Url:</label>
            <input asp-for="@Model.MenuItem.ImageUrl" class="form-control">
            <span asp-validation-for="@Model.MenuItem.ImageUrl" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.MenuItem.Description">Description:</label>
            <textarea asp-for="@Model.MenuItem.Description" class="form-control" placeholder="Enter Description"></textarea>
            <span asp-validation-for="@Model.MenuItem.Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.MenuItem.Price">Price:</label>
            <input asp-for="@Model.MenuItem.Price" class="form-control">
            <span asp-validation-for="@Model.MenuItem.Price" class="text-danger"></span>
        </div>
        <input asp-for="@Model.MenuItem.DateCreated" type="hidden" />
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

PizzaPlace/Pages/Dashboard/EditOffer.cshtml
@page
@model PizzaPlace.Pages.Dashboard.EditOfferModel
@{
    ViewData["Title"] = "EditOffer";
    Layout = "_LayoutDashboard";
}

<h1>EditOffer</h1>

<div class="container" style="background-color:#dadada; margin-top:20px; padding:20px;">
    <form asp-page="EditOffer" method="post">
        <input asp-for="@Model.Offer.Id" type="hidden" />
        <div class="form-group">
            <label asp-for="@Model.Offer.Title">Title:</label>
            <input asp-for="@Model.Offer.Title" class="form-control" placeholder="Enter Title">
            <span asp-validation-for="@Model.Offer.Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Offer.Description">Description:</label>
            <textarea asp-for="@Model.Offer.Description" class="form-control" placeholder="Enter Description"></textarea>
            <span asp-validation-for="@Model.Offer.Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Offer.Price">Price:</label>
            <input asp-for="@Model.Offer.Price" class="form-control">
            <span asp-validation-for="@Model.Offer.Price" class="text-danger"></span>
        </div>
        <input asp-for="@Model.Offer.DateCreated" type="hidden" />
        <button type="submit" class="btn btn-primary">Order</button>
    </form>
</div>

PizzaPlace/Pages/Dashboard/FeedbacksList.cshtml
@page
@model PizzaPlace.Pages.Dashboard.FeedbacksListModel
@{
    ViewData["Title"] = "FeedbacksList";
    Layout = "_LayoutDashboard";
}

<h1>Feedbacks List</h1>

<div class="container">
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Surname</th>
                <th>Email Adress</th>
                <th>Message</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var feedback in Model.Feedbacks)
            {
                <tr>
                    <td>@feedback.Name</td>
                    <td>@feedback.Surname</td>
                    <td>@feedback.EmailAdress</td>
                    <td>@feedback.Message</td>
                </tr>
            }
        </tbody>
    </table>
</div>

PizzaPlace/Pages/Dashboard/Menu.cshtml
@page
@model PizzaPlace.Pages.Dashboard.MenuModel
@{
    ViewData["Title"] = "Menu";
    Layout = "_LayoutDashboard";
}

    <h1 style="text-align:center">Menu</h1>

    <div class="container">
        @if (User.IsInRole("Admin"))
        {
            <h2>Orders: </h2>
            <a asp-page="OrdersList" class="btn btn-secondary">All</a>
            <a asp-page="OrdersList" asp-page-handler="NotProcessed" class="btn btn-secondary">Not processed</a>
            <a asp-page="OrdersList" asp-page-handler="Processed" class="btn btn-secondary">Processed</a>
            <a asp-page="OrdersList" asp-page-handler="Done" class="btn btn-secondary">Done</a>
            <h2>Users: </h2>
            <a asp-page="UsersList" class="btn btn-secondary">Users</a>
            <a href="/Admin/Register" class="btn btn-secondary">Create User</a>
            <h2>Offers</h2>
            <a asp-page="OffersList" class="btn btn-secondary">Manage Offers</a>
            <h2>Menu Items</h2>
            <a asp-page="MenuItemsList" class="btn btn-secondary">Manage Menu Items</a>
            <h2>Feedbacks</h2>
            <a asp-page="FeedbacksList" class="btn btn-secondary">View All Feedbacks</a>
        }

        @if (User.IsInRole("Cook"))
        {
            <h2>Orders: </h2>
            <a asp-page="OrdersList" asp-page-handler="NotProcessed" class="btn btn-secondary">Not processed</a>
        }

        @if (User.IsInRole("Delivery"))
        {
            <h2>Orders: </h2>
            <a asp-page="OrdersList" asp-page-handler="Processed" class="btn btn-secondary">Processed</a>
        }
    </div>

PizzaPlace/Pages/Dashboard/MenuItemsList.cshtml
@page
@model PizzaPlace.Pages.Dashboard.MenuItemsListModel
@{
    ViewData["Title"] = "MenuItemsList";
    Layout = "_LayoutDashboard";
}

<h1 style="text-align:center;">MenuItemsList</h1>

<div class="container">
    <a asp-page="CreateMenuItem" class="btn btn-secondary">Create Menu Item</a>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Title</th>
                <th>DateCreated</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.MenuItems)
            {
                <tr>
                    <td>@item.Title</td>
                    <td>@item.DateCreated.ToString("dd MMMM yyyy")</td>
                    <td>
                        <a asp-page="EditMenuItem" asp-route-id="@item.Id">Edit</a> |
                        <a asp-page-handler="DeleteMenuItem" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to delete @item.Title?')">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

PizzaPlace/Pages/Dashboard/OffersList.cshtml
@page
@model PizzaPlace.Pages.Dashboard.OffersListModel
@{
    ViewData["Title"] = "OffersList";
    Layout = "_LayoutDashboard";
}

<h1 style="text-align:center">OffersList</h1>


<div class="container">
    <a asp-page="CreateOffer" class="btn btn-secondary">Create Offer</a>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Title</th>
                <th>DateCreated</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var offer in Model.Offers)
            {
                <tr>
                    <td>@offer.Title</td>
                    <td>@offer.DateCreated.ToString("dd MMMM yyyy")</td>
                    <td>
                        <a asp-page="EditOffer" asp-route-id="@offer.Id">Edit</a> | 
                        <a asp-page-handler="DeleteOffer" asp-route-id="@offer.Id" onclick="return confirm('Are you sure you want to delete @offer.Title?')">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

PizzaPlace/Pages/Dashboard/OrdersList.cshtml
@page
@model PizzaPlace.Pages.ViewOrdersModel
@{
    ViewData["Title"] = "ViewOrders";
    Layout = "_LayoutDashboard";
}
    <div class="container">
        <h1>Orders List</h1>
        @if (User.IsInRole("Admin"))
        {
            <a asp-page="OrdersList" class="btn btn-secondary">All</a>
            <a asp-page="OrdersList" asp-page-handler="NotProcessed" class="btn btn-secondary">Not processed</a>
            <a asp-page="OrdersList" asp-page-handler="Processed" class="btn btn-secondary">Processed</a>
            <a asp-page="OrdersList" asp-page-handler="Done" class="btn btn-secondary">Done</a>
        }

        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Adress</th>
                    <th>Phone</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Orders)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Address</td>
                        <td>@item.Phone</td>
                        @if (!item.IsProccessed)
                        {
                            <td>
                                <a asp-page-handler="SetProcessed" asp-route-id="@item.Id">Set Processed</a>
                            </td>
                        }
                        else if (!item.IsDelivered)
                        {
                            <td>
                                <a asp-page-handler="SetDelivered" asp-route-id="@item.Id">Set Delivered</a>
                            </td>
                        }
                        else
                        {
                            <td class="text-success">Done</td>
                        }
                    </tr>
                }
            </tbody>


        </table>
    </div>

PizzaPlace/Pages/Dashboard/UsersList.cshtml
@page
@using Microsoft.AspNetCore.Identity;
@model PizzaPlace.Pages.Dashboard.UsersListModel
@{
    ViewData["Title"] = "UsersList";
    Layout = "_LayoutDashboard";
}

@inject UserManager<IdentityUser> UserManager

<h1 style="text-align:center">Users List</h1>

<div class="container">
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Email</th>
                <th>Roles</th>
                <th>Manage Roles</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model.Users)
            {
                <tr>
                    <td>@user.Email</td>
                    <td>
                        @foreach (var role in await UserManager.GetRolesAsync(user))
                        {
                            <p>@role</p>
                        }
                    </td>
                    <td>
                        @foreach (var role in Model.Roles)
                        {
                            if (await UserManager.IsInRoleAsync(user, role.Name))
                            {
                                <p>
                                    <a asp-page-handler="RemoveRole" asp-route-roleName="@role.Name" asp-route-userId="@user.Id" class="text-danger">Remove @role.Name.ToLower() role</a>
                                </p>
                            }
                            else
                            {
                                <p>
                                    <a asp-page-handler="AddRole" asp-route-roleName="@role.Name" asp-route-userId="@user.Id" class="text-success">Add @role.Name.ToLower() role</a>
                                </p>
                            }
                        }
                    </td>
                    <td>
                        <a asp-page-handler="DeleteUser" asp-route-id="@user.Id" onclick="return confirm('Are you sure you want to delete @user.Email')">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>