PizzaPlace/Models/Feedback.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PizzaPlace.Models
{
    public class Feedback
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public string EmailAdress { get; set; }
        [Required]
        public string Message { get; set; }
        [Required]
        public DateTime DateCreated { get; set; }
    }
}

PizzaPlace/Models/Order.cs
using System.ComponentModel.DataAnnotations;

namespace PizzaPlace.Models
{
    public class Order
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [Phone]
        public string Phone { get; set; }
        [Required]
        public string Message { get; set; }
        [Required]
        public bool IsProccessed { get; set; }
        [Required]
        public bool IsDelivered { get; set; }
    }
}

PizzaPlace/ViewModels/FeedbackViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PizzaPlace.ViewModels
{
    public class FeedbackViewModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public string EmailAdress { get; set; }
        [Required]
        public string Message { get; set; }
    }
}

PizzaPlace/ViewModels/MenuViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PizzaPlace.ViewModels
{
    public class MenuViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public double Price { get; set; }
        [Required]
        public string ImageUrl { get; set; }
        public DateTime DateCreated { get; set; }
    }
}

PizzaPlace/ViewModels/OrderViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PizzaPlace.ViewModels
{
    public class OrderViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [Phone]
        public string Phone { get; set; }
        [Required]
        public string Message { get; set; }
        public bool IsProccessed { get; set; }
        public bool IsDelivered { get; set; }
    }
}

PizzaPlace/Pages/Confirmation.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PizzaPlace.Pages
{
    public class ConfirmationModel : PageModel
    {
        public string Message { get; set; }
        public void OnGetOrder()
        {
            Message = "Thank you for ordering!!!";
        }
        public void OnGetSubscription()
        {
            Message = "Thanks for subscribing!!!";
        }
        public void OnGetFeedback()
        {
            Message = "Thanks for your feedback!!!";
        }
    }
}

PizzaPlace/Pages/Dashboard/Menu.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PizzaPlace.Pages.Dashboard
{
    [Authorize]
    public class MenuModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

PizzaPlace/Pages/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;

namespace PizzaPlace.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly IMenuItemService menuItemService;

        public DetailsModel(IMenuItemService menuItemService)
        {
            this.menuItemService = menuItemService;
        }
        public MenuViewModel MenuViewModel { get; set; }
        public void OnGet(int id)
        {
            MenuItem menuItem = menuItemService.GetById(id);
            MenuViewModel = new MenuViewModel()
            {
                Id = menuItem.Id,
                Title = menuItem.Title,
                Description = menuItem.Description,
                DateCreated = menuItem.DateCreated,
                Price = menuItem.Price,
                ImageUrl = menuItem.ImageUrl
            };
        }
    }
}

PizzaPlace/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PizzaPlace.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PizzaPlace/Pages/Feedback.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System;

namespace PizzaPlace.Pages
{
    public class FeedbackModel : PageModel
    {
        private readonly IFeedbackService feedbackService;

        public FeedbackModel(IFeedbackService feedbackService)
        {
            this.feedbackService = feedbackService;
        }
        [BindProperty]
        public FeedbackViewModel Feedback { get; set; }
        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                Feedback feedback = new Feedback()
                {
                    Name = Feedback.Name,
                    Surname = Feedback.Surname,
                    EmailAdress = Feedback.EmailAdress,
                    Message = Feedback.Message,
                    DateCreated = DateTime.Now,
                };

                feedbackService.Add(feedback);

                return RedirectToPage("Confirmation", "Feedback");
            }
            else
            {
                return Page();
            }
        }
    }
}

PizzaPlace/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PizzaPlace.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IOfferService offerService;

        public IndexModel(IOfferService offerService)
        {
            this.offerService = offerService;
        }
        public List<OfferViewModel> OfferViewModels { get; set; }
        public void OnGet()
        {
            OfferViewModels = offerService.GetAll().Select(x => new OfferViewModel
            {
                Title = x.Title,
                Description = x.Description,
                DateCreated = x.DateCreated,
                Price = x.Price,
            }).ToList();

        }
    }
}

PizzaPlace/Pages/Menu.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PizzaPlace.Pages
{
    public class MenuModel : PageModel
    {
        private readonly IMenuItemService menuItemService;

        public MenuModel(IMenuItemService menuItemService)
        {
            this.menuItemService = menuItemService;
        }
        public List<MenuViewModel> MenuViewModels { get; set; }
        public void OnGet()
        {
            MenuViewModels = menuItemService.GetAll().Select(x => new MenuViewModel 
            {
                Id = x.Id,
                Title = x.Title,
                Description = x.Description,
                ImageUrl = x.ImageUrl,
                Price = x.Price,
                DateCreated = x.DateCreated,
            }).ToList();
        }
    }
}

PizzaPlace/Pages/Order.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System;

namespace PizzaPlace.Pages
{
    public class OrderModel : PageModel
    {
        private readonly IOrderService orderService;
        private readonly ISubscriptionService subscriptionService;

        public OrderModel(IOrderService orderService, ISubscriptionService subscriptionService)
        {
            this.orderService = orderService;
            this.subscriptionService = subscriptionService;
        }
        [BindProperty]
        public OrderViewModel Order { get; set; }
        public string ErrorMessage { get; set; }
        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                Order order = new Order()
                {
                    Name = Order.Name,
                    Address = Order.Address,
                    Surname = Order.Surname,
                    Phone = Order.Phone,
                    Message = Order.Message
                };

                orderService.Add(order);
                return RedirectToPage("Confirmation", "Order");
            }
            else
            {
                return Page();
            }
        }
        public IActionResult OnPostSubscribe(string email)
        {
            if (!String.IsNullOrEmpty(email))
            {
                subscriptionService.Add(email);
                return RedirectToPage("Confirmation", "Subscription");
            }
            else
            {
                ErrorMessage = "Please Enter Email";
                return Page();
            }
        }
    }
}

PizzaPlace/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PizzaPlace.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PizzaPlace/Pages/Confirmation.cshtml
@page
@model PizzaPlace.Pages.ConfirmationModel
@{
    ViewData["Title"] = "Confirmation";
}

<h1 class="alert-success" style="text-align:center; padding:20px">@Model.Message</h1>

PizzaPlace/Pages/Details.cshtml
@page "{id}"
@model PizzaPlace.Pages.DetailsModel
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div class="container">
    <img src="@Model.MenuViewModel.ImageUrl" />
    <h1 style="text-align:center">@Model.MenuViewModel.Title</h1>

    <p style="text-align:center">@Model.MenuViewModel.Description</p>

    <h2>Price: @Model.MenuViewModel.Price</h2>
</div>

PizzaPlace/Pages/Feedback.cshtml
@page
@model PizzaPlace.Pages.FeedbackModel
@{
    ViewData["Title"] = "Feedback";
}

<h1>Feedback</h1>

<div class="container" style="background-color:#dadada; margin-top:20px; padding:20px;">
    <form asp-page="Feedback" method="post">
        <div class="form-group">
            <label asp-for="@Model.Feedback.Name">Name:</label>
            <input asp-for="@Model.Feedback.Name" class="form-control" placeholder="Enter name">
            <span asp-validation-for="@Model.Feedback.Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Feedback.Surname">Surname:</label>
            <input asp-for="@Model.Feedback.Surname" class="form-control" placeholder="Enter Surname">
            <span asp-validation-for="@Model.Feedback.Surname" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Feedback.EmailAdress">Email:</label>
            <input asp-for="@Model.Feedback.EmailAdress" class="form-control" placeholder="Enter Email">
            <span asp-validation-for="@Model.Feedback.EmailAdress" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Feedback.Message">Message:</label>
            <textarea asp-for="@Model.Feedback.Message" class="form-control" placeholder="Enter Message"></textarea>
            <span asp-validation-for="@Model.Feedback.Message" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Order</button>
    </form>
</div>

PizzaPlace/Pages/Index.cshtml
@page 
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" style="width:100%; height:500px !important">
            <div class="carousel-item active">
                <img class="d-block w-100" src="https://www.pizza-bugs-fun.com/images/stories/pizza.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/j/l/p53936-15526488305c8b8a7eb210f.jpg?tr=tr:n-xlarge" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://media-cdn.tripadvisor.com/media/photo-s/18/1a/d5/1e/casteloes.jpg" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="container" style="background-color:#dadada; text-align:center; margin-top:2%; padding:2%;">
        <h2>Special Offers</h2>
        @if (Model.OfferViewModels.Count == 0)
        {
            <p style="margin-top:2%;">No offers to display</p>
        }
        else
        {
            foreach (var offer in Model.OfferViewModels)
            {
                <div class="card text-center" style="margin-top:2%;">
                    <div class="card-body">
                        <h5 class="card-title">@offer.Title</h5>
                        <p class="card-text">@offer.Description</p>
                        <p class="card-text">Price: @offer.Price</p>
                    </div>
                    <div class="card-footer text-muted">
                        Created: @offer.DateCreated.ToString("dd MMMM yyyy")
                    </div>
                </div>
            }
        }
    </div>

PizzaPlace/Pages/Menu.cshtml
@page
@model PizzaPlace.Pages.MenuModel
@{
    ViewData["Title"] = "Menu";
}

<h1>Menu</h1>

@if(Model.MenuViewModels.Count == 0)
{
    <p>No Menu Items To show</p> 
}
else
{
<div class="row">
    @foreach (var item in Model.MenuViewModels)
    {
        <div class="col-md-3">
            <div class="card">
                <img class="card-img-top" src="@item.ImageUrl" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">@item.Title</h5>
                    <p class="card-text">@item.Description</p>
                    <p class="card-text">Price: @item.Price</p>
                    <a asp-page="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
    }
</div>
}

PizzaPlace/Pages/Order.cshtml
@page
@model PizzaPlace.Pages.OrderModel
@{
    ViewData["Title"] = "Order";
}

<h1>Order</h1>
<div class="container" style="background-color:#dadada; margin-top:20px; padding:20px;">
    <form asp-page="Order" method="post">
        <div class="form-group">
            <label asp-for="@Model.Order.Name">Name:</label>
            <input asp-for="@Model.Order.Name" class="form-control" placeholder="Enter name">
            <span asp-validation-for="@Model.Order.Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Order.Surname">Surname:</label>
            <input asp-for="@Model.Order.Surname" class="form-control" placeholder="Enter Surname">
            <span asp-validation-for="@Model.Order.Surname" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Order.Address">Address:</label>
            <input asp-for="@Model.Order.Address" class="form-control" placeholder="Enter Address">
            <span asp-validation-for="@Model.Order.Address" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Order.Phone ">Phone :</label>
            <input asp-for="@Model.Order.Phone " class="form-control" placeholder="Enter Phone ">
            <span asp-validation-for="@Model.Order.Phone " class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Order.Message">Message:</label>
            <textarea asp-for="@Model.Order.Message" class="form-control" placeholder="Enter Message"></textarea>
            <span asp-validation-for="@Model.Order.Message" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Order</button>
    </form>
</div>



<div class="container" style="background-color:#dadada; margin-top:2%; padding:2%;">
    @if (!String.IsNullOrEmpty(Model.ErrorMessage))
    {
        <div class="alert-danger" style="text-align:center; padding:2%">@Model.ErrorMessage</div>
    }
        <form asp-page="Order" asp-page-handler="Subscribe" method="post">
            <h1>Subscribe:</h1>
            <div class="form-group">
                <label for="email">Email address:</label>
                <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <button type="submit" class="btn btn-primary">Subscribe</button>
        </form>
</div>